---
apiVersion: v1
kind: Pod
metadata:
  name: restart-never
spec:
  containers:
    - name: restart-never
      image: alpine:3
      command:
        - sleep
        - "2"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: restart-nopolicy
spec:
  containers:
    - name: restart-nopolicy
      image: alpine:3
      command:
        - sleep
        - "2"