---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-1
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine:latest
            args:
             - sleep
             - "10s"
          restartPolicy: OnFailure
