---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-mount
spec:
  containers:
    - name: alpine
      image: alpine:3
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: mysecret
          mountPath: /secrets
  volumes:
    - name: mysecret
      secret:
        secretName: hello-secret