---
{{- with .Values.apps.makeline }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6}}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 6 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: {{ .container.image }}:{{ .container.tag }}
          ports: {{ .container.ports | toYaml | nindent 12 }}
          env:
{{- range .container.env }}
            - name: {{ .name }}
              value: {{ .value }}
{{- end }} 
          resources:
            requests:
              cpu: 1m
              memory: 6Mi
            limits:
              cpu: 5m
              memory: 20Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
{{- end }}
---
{{- with .Values.services.makeline }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type }}
  ports: {{ .ports | toYaml | nindent 4 }}
  selector: {{ .selector | toYaml | nindent 4 }}
{{- end }}