---
{{- with .Values.apps.product }}
apiVersion: apps/v1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels: {{ .selector | toYaml | nindent 6 }}
  template:
    metadata:
      labels: {{ .labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: product-service
          image: {{ .container.image }}:{{ .container.tag }}
          ports: {{ .container.ports | toYaml | nindent 12 }}
          env:
{{- range .container.env }}
            - name: {{ .name }}
              value: {{ .value }}
{{- end }}
          resources: {{ .container.resources | toYaml | nindent 12 }}
          readinessProbe: {{ .container.readinessProbe | toYaml | nindent 12 }}
          livenessProbe: {{ .container.livenessProbe | toYaml | nindent 12 }}
{{- end }}
---
{{- with .Values.services.product }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type }}
  ports: {{ .ports | toYaml | nindent 4 }}
  selector: {{ .selector | toYaml | nindent 4 }}
{{- end }}