---
apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
    - name: httpd
      image: httpd:alpine
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 500m
          memory: 256M