---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-norestart
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command:
        - /bin/bash
        - -ec
        - touch /tmp/qt; sleep 30; rm /tmp/qt; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/qt
        initialDelaySeconds: 5
        periodSeconds: 5