---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-ds
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: logagent
          image: fluent/fluentd:edge-debian
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 300m
          ports:
            - containerPort: 9880
              name: fluentd
