---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32767