---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    me: controller
    type: rs
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: web
      env: dev
  template:
    metadata:
      labels:
        app: web
        env: dev
        srv: nginx
    spec:
      containers:
        - name: web
          image: nginx
