---
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-demo
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - sleep
      - 1d
    envFrom:
      - configMapRef:
          name: sample-cm
    
