---
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-demo
  labels:
    name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: sample-cm
      volumeMounts:
        - name: cm
          mountPath: /config
  volumes:
    - name: cm
      configMap:
        name: sample-cm
    
    
