---
apiVersion: v1
kind: Pod
metadata:
  name: gameoflife
spec:
  containers:
    - image: qualitythought/gameoflife:07112020
      name: gol
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
      ports:
        - containerPort: 8080
          name: golhttpport
          protocol: TCP
