apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logagent
spec:
  selector:
    matchLabels:
      name: logagent
  template:
    metadata:
      labels:
        name: logagent
    spec:
      containers:
      - name:  logagent  
        image: alpine
        command:
          - sleep
          - 1d
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
