---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: download-job
  namespace: my-namespace
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    metadata:
      name: download-job
      namespace: my-namespace
    spec:
      template:
        metadata:
          name: download-job
          namespace: my-namespace
        spec:
          restartPolicy: OnFailure
          containers:
            - name: download
              image: alpine:3
              command:
                - wget
                - https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
