---
apiVersion: v1
kind: Pod
metadata:
  name: resource-requirements-demo
spec:
  containers:
    - name: container-with-limits
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "512M"
          cpu: "1"
        requests:
          memory: "64M"
          cpu: "0.5"
