---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-service
  annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: books-svc
  template:
    metadata:
      labels:
        app: books-svc
    spec:
      containers:
        - name: books-service
          image: shaikkhajaibrahim/libbookssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          envFrom:
            - configMapRef:
                name: books-svc-config
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  type: ClusterIP
  selector:
    app: users-svc
  ports:
  - port: 8000
    targetPort: 8000
