---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-db-config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-db-config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booksdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-svc-config
data:
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
  DATABASE_URL: "postgresql://user:password@users-db:5432/usersdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-svc-config
data:
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
  DATABASE_URL: "postgresql://user:password@books-db:5432/booksdb"