---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
data:
  MYSQL_ROOT_PASSWORD: YWRtaW5AMTIz
  MYSQL_DATABASE: bGVhcm5pbmc=
  MYSQL_USER: ZGV2b3Bz
  MYSQL_PASSWORD: ZGV2b3BzQDEyMw==

---
apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
    - name: db
      image: mysql:9
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: db-secrets
      volumeMounts:
        - name: db-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: db-vol
      persistentVolumeClaim:
        claimName: db-vol 
