---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    project: learning
    team: devops
    app: spc
    version: v1
spec:
  minReadySeconds: 45
  replicas: 4
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        project: learning
        team: devops
        app: spc
        version: v1
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/febspc:1
          resources:
            requests:
              cpu: 10m
              memory: 100M
            limits:
              cpu: 300m
              memory: 300M
          ports:
            - name: spc-port
              containerPort: 8080
          startupProbe:
            exec:
              command:
                - pwd
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: LoadBalancer
  selector:
    app: spc
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
            
      