service:
  name: nginx-svc
  type: LoadBalancer
  selector: 
    app: nginx
  port:
    protocol: TCP
    port: 80
    targetPort: 80
deployment:
  name: nginx-deploy
  replicas: 2
  image: nginx:latest
  containerPort: 80