---
apiVersion: v1
kind: Pod
metadata:
  name: vol-demo
spec:
  containers:
    - name: test 
      image: alpine
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: test-vol
          mountPath: /tools
  volumes:
    - name: test-vol
      emptyDir: