---
apiVersion: v1
kind: Pod
metadata:
  name: bestefforts
  labels:
    app: httpd
    purpose: learning
    env: dev
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - name: httpd
          protocol: TCP
          containerPort: 80