---
apiVersion: v1
kind: Pod
metadata:
  name: guranteed
  labels:
    app: httpd
    purpose: learning
    env: dev
spec:
  containers:
    - name: httpd
      image: httpd:latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      ports:
        - name: httpd
          protocol: TCP
          containerPort: 80