---
apiVersion: v1
kind: Pod
metadata:
  name: failure-1
  labels:
    app: httpd
    purpose: learning
    env: dev
spec:
  containers:
    - name: tomcat
      image: tomcat:latest
      resources:
        limits:
          cpu: "100m"
          memory: "20Mi"
        requests:
          cpu: "100m"
          memory: "10Mi"
      ports:
        - name: httpd
          protocol: TCP
          containerPort: 8080