apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nop-retain
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_ZRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true