apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
    app: alpine-demo
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "echo 'Hello from Alpine Pod'; sleep 3600"]
      volumeMounts:
        - name: sample-vol
          mountPath: /sample-directory
  volumes:
    - name: sample-vol
      emptyDir: {}
