---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels:
    app: spc
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: spc
      env: dev
  template:
    metadata:
      labels:
        app: spc
        env: dev
        version: v1.6.9
    spec:
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 500m