---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    purpose: rsdemo
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - jenkins
          - hudson
      - key: release
        operator: Exists
  template:
    metadata:
      labels:
        app: jenkins
        release: v1.1
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              protocol: TCP

