---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    env: dev
    topic: replicaset
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
        env: dev
        topic: pod
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"