---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  annotations:
    kubernetes.io/change-cause: "version v1.0"
spec:
  minReadySeconds: 1
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
        version: v1.0
    spec:
      containers:
        - name: web
          image: shaikkhajaibrahim/dmtest:1.0
          resources:
            requests:
              memory: 24Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 200m
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-sv
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
