---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  annotations:
    kubernetes.io/change-cause: v2 deployment to slim version
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - web
          - nginx
          - apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: nginx
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          startupProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 2
            tcpSocket:
              port: 80
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 80
          