---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector: {{ .Values.selector | toYaml | nindent 4 }}
  ports: 
  {{- range .Values.service.ports }}
    - {{ . | toYaml  | indent 6 | trim }}
  {{- end }}
