---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
  - protocol: {{ .Values.service.port.protocol }}
    port: {{ .Values.service.port.port }}
    targetPort: {{ .Values.service.port.targetPort }}