---
apiVersion: v1
kind: Pod
metadata:
  name: activity1
  labels:
    app: nop
    env: dev
    purpose: understanding
spec:
  containers:
    - name: nop
      image: shaikkhajaibrahim/nopcommercejune2024:070624
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "64Mi"
          