---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  minReadySeconds: 10
  ordinals:
    start: 1
  replicas: 2
  selector:
    matchLabels:
      app: db
  serviceName: mysql-svc
  volumeClaimTemplates:
    - metadata:
        name: dbvol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:9
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/mysql
            
